# Build stage
FROM registry.redhat.io/ubi9/go-toolset@sha256:2dd6e7ca3d9d10d25b51239c8f183aeefa17fdc0d40b3468f9d4166ab6c95f78 AS builder

WORKDIR /app

COPY . .

ENV CGO_ENABLED=1 \
    GOEXPERIMENT=strictfipsruntime

RUN go mod vendor
RUN go build -buildvcs=false -o rekor_monitor ./cmd/rekor_monitor

# Final stage
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:55443bd3d9272fd166145bc19042f976b7c6cc8ca2112b2461936d5d09740f4d

COPY --from=builder /app/rekor_monitor /rekor_monitor

LABEL description="rekor_monitor is a monitoring tool for the Rekor transparency log."
LABEL io.k8s.description="rekor_monitor is a monitoring tool for the Rekor transparency log."
LABEL io.k8s.display-name="rekor-monitor container image for Red Hat Trusted Signer"
LABEL io.openshift.tags="rekor-monitor trusted-signer"
LABEL summary="Provides the rekor_monitor binary for continuously monitoring the transparency log state of a Rekor server, performing consistency checks."
LABEL com.redhat.component="rekor-monitor"
LABEL name="rhtas/rekor-monitor-rhel9"

COPY LICENSE /licenses/LICENSE

USER 65532:65532

#ENTRYPOINT
ENTRYPOINT ["/rekor_monitor"]
