# Build stage
FROM registry.redhat.io/ubi9/go-toolset@sha256:2bf39c00d96ada8f0b716b0500c01d558dafe838f5a9c2957b3acd2759e7d90e AS builder

WORKDIR /app

COPY . .

ENV CGO_ENABLED=1 \
    GOEXPERIMENT=strictfipsruntime

RUN go mod vendor
RUN go build -buildvcs=false -o ctlog_monitor ./cmd/ct_monitor

# Final stage
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:b061cda54b60dbe0c4746369a0af84b914af226e19cde4612b62e2e12e4371e6

COPY --from=builder /app/ctlog_monitor /ctlog_monitor

LABEL description="ctlog_monitor is a monitoring tool for the certificate transparency log."
LABEL io.k8s.description="ctlog_monitor is a monitoring tool for the certificate transparency log."
LABEL io.k8s.display-name="ctlog-monitor container image for Red Hat Trusted Signer"
LABEL io.openshift.tags="ctlog-monitor trusted-signer"
LABEL summary="Provides the ctlog_monitor binary for continuously monitoring the transparency log state of a Ctlog server, performing consistency checks."
LABEL com.redhat.component="ctlog-monitor"
LABEL name="rhtas/ctlog-monitor-rhel9"

COPY LICENSE /licenses/LICENSE

USER 65532:65532

#ENTRYPOINT
ENTRYPOINT ["/ctlog_monitor"]
