# Build stage
FROM registry.redhat.io/ubi9/go-toolset:9.8-1783679445@sha256:11d7094120f37623648695c4f1e622e2f02f8dde184ff6b0ef89a9761be7d49e AS builder

WORKDIR /app

COPY . .

RUN go mod vendor
RUN go build -buildvcs=false -o rekor_monitor ./cmd/rekor_monitor

# Final stage
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:8201445bebcb5bd4fe23fcc2a76cd5fec029ab401d270926a1563c03b36f0137

COPY --from=builder /app/rekor_monitor /rekor_monitor

LABEL description="rekor_monitor is a monitoring tool for the Rekor transparency log."
LABEL io.k8s.description="rekor_monitor is a monitoring tool for the Rekor transparency log."
LABEL io.k8s.display-name="rekor-monitor container image for Red Hat Trusted Signer"
LABEL io.openshift.tags="rekor-monitor trusted-signer"
LABEL summary="Provides the rekor_monitor binary for continuously monitoring the transparency log state of a Rekor server, performing consistency checks."
LABEL com.redhat.component="rekor-monitor"
LABEL name="rhtas/rekor-monitor-rhel9"

COPY LICENSE /licenses/LICENSE

USER 65532:65532

#ENTRYPOINT
ENTRYPOINT ["/rekor_monitor"]
