# Build stage
FROM registry.redhat.io/ubi9/go-toolset@sha256:0706c592277dc4ea08b4ee7859d9e6ba978fed4dde78278624bf7bee91eddc10 AS builder

WORKDIR /app

COPY . .

ENV CGO_ENABLED=1 \
    GOEXPERIMENT=strictfipsruntime

RUN go mod vendor
RUN go build -buildvcs=false -o rekor_monitor ./cmd/rekor_monitor

# Final stage
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:77bad043ffe39eb92b2346e935fa3023e3d072e93de21562f33847e42f3612e4

COPY --from=builder /app/rekor_monitor /rekor_monitor

LABEL description="rekor_monitor is a monitoring tool for the Rekor transparency log."
LABEL io.k8s.description="rekor_monitor is a monitoring tool for the Rekor transparency log."
LABEL io.k8s.display-name="rekor-monitor container image for Red Hat Trusted Signer"
LABEL io.openshift.tags="rekor-monitor trusted-signer"
LABEL summary="Provides the rekor_monitor binary for continuously monitoring the transparency log state of a Rekor server, performing consistency checks."
LABEL com.redhat.component="rekor-monitor"
LABEL name="rhtas/rekor-monitor-rhel9"

COPY LICENSE /licenses/LICENSE

USER 65532:65532

#ENTRYPOINT
ENTRYPOINT ["/rekor_monitor"]
