[project]
name = "rekor-monitor"
version = "1.0"
description = "A monitor for Rekor logs using Prometheus"
requires-python = ">=3.11"

dependencies = [
    'prometheus_client>=0.19.0'
]

[tool.setuptools.packages.find]
where = ["."]
